## Automatically generated by odin 1.2.4 - do not edit
odin_stoch_model_si_binom_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "odin_stoch_model_si_binom_rhs_dde"),
    dll = "HospitalSpreading",
    user = c("beta", "d", "i_initial", "n_hospitals", "s_initial"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("odin_stoch_model_si_binom_rhs_dde", package = "HospitalSpreading")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("odin_stoch_model_si_binom_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "HospitalSpreading")
    },

    update_metadata = function() {
      meta <- .Call("odin_stoch_model_si_binom_metadata", private$ptr,
                    PACKAGE = "HospitalSpreading")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("odin_stoch_model_si_binom_create", user, PACKAGE = "HospitalSpreading")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/odin_stoch_model_si_binom.json", mustWork = TRUE,
                             package = "HospitalSpreading")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("odin_stoch_model_si_binom_set_user", private$ptr, user, PACKAGE = "HospitalSpreading")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("odin_stoch_model_si_binom_initial_conditions", private$ptr, step, PACKAGE = "HospitalSpreading")
    },

    rhs = function(step, y) {
      .Call("odin_stoch_model_si_binom_rhs_r", private$ptr, step, y, PACKAGE = "HospitalSpreading")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("odin_stoch_model_si_binom_contents", private$ptr, PACKAGE = "HospitalSpreading")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


odin_stoch_model_si_binom <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("odin_stoch_model_si_binom")
  odin_stoch_model_si_binom_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(odin_stoch_model_si_binom) <- "odin_generator"
attr(odin_stoch_model_si_binom, "generator") <- odin_stoch_model_si_binom_
odin_stoch_model_si_poisson_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "odin_stoch_model_si_poisson_rhs_dde"),
    dll = "HospitalSpreading",
    user = c("beta", "d", "i_initial", "n_hospitals", "s_initial"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("odin_stoch_model_si_poisson_rhs_dde", package = "HospitalSpreading")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("odin_stoch_model_si_poisson_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "HospitalSpreading")
    },

    update_metadata = function() {
      meta <- .Call("odin_stoch_model_si_poisson_metadata", private$ptr,
                    PACKAGE = "HospitalSpreading")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("odin_stoch_model_si_poisson_create", user, PACKAGE = "HospitalSpreading")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/odin_stoch_model_si_poisson.json", mustWork = TRUE,
                             package = "HospitalSpreading")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("odin_stoch_model_si_poisson_set_user", private$ptr, user, PACKAGE = "HospitalSpreading")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("odin_stoch_model_si_poisson_initial_conditions", private$ptr, step, PACKAGE = "HospitalSpreading")
    },

    rhs = function(step, y) {
      .Call("odin_stoch_model_si_poisson_rhs_r", private$ptr, step, y, PACKAGE = "HospitalSpreading")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("odin_stoch_model_si_poisson_contents", private$ptr, PACKAGE = "HospitalSpreading")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


odin_stoch_model_si_poisson <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("odin_stoch_model_si_poisson")
  odin_stoch_model_si_poisson_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(odin_stoch_model_si_poisson) <- "odin_generator"
attr(odin_stoch_model_si_poisson, "generator") <- odin_stoch_model_si_poisson_
odin_stoch_model_sis_binom_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "odin_stoch_model_sis_binom_rhs_dde"),
    dll = "HospitalSpreading",
    user = c("alpha", "beta", "com_p", "d", "i_initial", "N", "n_subpop",
             "s_initial", "w_in", "w_out"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("odin_stoch_model_sis_binom_rhs_dde", package = "HospitalSpreading")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("odin_stoch_model_sis_binom_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "HospitalSpreading")
    },

    update_metadata = function() {
      meta <- .Call("odin_stoch_model_sis_binom_metadata", private$ptr,
                    PACKAGE = "HospitalSpreading")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("odin_stoch_model_sis_binom_create", user, PACKAGE = "HospitalSpreading")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/odin_stoch_model_sis_binom.json", mustWork = TRUE,
                             package = "HospitalSpreading")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("odin_stoch_model_sis_binom_set_user", private$ptr, user, PACKAGE = "HospitalSpreading")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("odin_stoch_model_sis_binom_initial_conditions", private$ptr, step, PACKAGE = "HospitalSpreading")
    },

    rhs = function(step, y) {
      .Call("odin_stoch_model_sis_binom_rhs_r", private$ptr, step, y, PACKAGE = "HospitalSpreading")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("odin_stoch_model_sis_binom_contents", private$ptr, PACKAGE = "HospitalSpreading")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


odin_stoch_model_sis_binom <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("odin_stoch_model_sis_binom")
  odin_stoch_model_sis_binom_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(odin_stoch_model_sis_binom) <- "odin_generator"
attr(odin_stoch_model_sis_binom, "generator") <- odin_stoch_model_sis_binom_
